//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailSenderLibrary.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SpamDatabase : DbContext
    {
        public SpamDatabase()
            : base("name=SpamDatabase")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Servers> ServersSet { get; set; }
        public virtual DbSet<Recepient> RecepientSet { get; set; }
        public virtual DbSet<SheluderTask> SheluderTaskSet { get; set; }
        public virtual DbSet<Sender> SenderSet { get; set; }
        public virtual DbSet<Email> EmailSet { get; set; }
        public virtual DbSet<MailingList> MailingListSet { get; set; }
    }
}
